version: '2.1'

services:
  docker-rest:
    container_name: docker-rest-db
    image: docker-rest:1.2
    build:
      context: .
    environment:
      LOG_LEVEL: TRACE
      JDBC_URL: 'jdbc:oracle:thin:@database:1521:XE'
    depends_on:
      docker-rest-db:
        condition: service_healthy
    links:
      - "docker-rest-db:database"
    volumes:
      - your_host_docker_data/logs:/logs
    ports:
      - "8081:8080"

  docker-rest-db:
    container_name: docker-rest
    image: daggerok/oracle:11.2.0.2-xe
    shm_size: 1g
    environment:
      ORACLE_PWD: password
      ORACLE_CHARACTERSET: AL32UTF8
    ports: ["1521:1521"]
    volumes:
      - your_host_docker_data/oradata:/u01/app/oracle/oradata
      - your_host_docker_data/startup:/u01/app/oracle/scripts/startup
